# fly.toml app configuration file generated for lol-champion-rotation on 2024-07-28T20:59:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lol-champion-rotation'
primary_region = 'waw'

[build]

[deploy]
  release_command = "./App migrate -y"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "/app/App serve --env production --hostname 0.0.0.0 --port 8080"
  cron = "supercronic /app/scripts/crontab"
