# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/run_tests
        with: 
          swift-version: "6.1.2"
          database-url: postgres://testuser:testpass@localhost:5432/testdb?sslmode=disable
  
  deploy:
    name: Deploy app
    needs: run-tests
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: scripts/setup-environment.sh
        env:
          FIREBASE_AUTH_KEY: ${{ secrets.FIREBASE_AUTH_KEY }}

      - name: Setup Fly.io cli
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build and deploy app
        run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
