# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: scripts/setup-environment.sh
        env:
          FIREBASE_AUTH_KEY: ${{ secrets.FIREBASE_AUTH_KEY }}

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
